import React from "react";
import { ArrowRight, CheckCircle2, ChevronRight, Clock3, Layers3, UsersRound } from "lucide-react";
import { Link } from "wouter";

const benefits = [
  ["01", "See the whole customer journey", "Keep customer context, lead history, appointments, and follow-up in one place so your office and field teams can move with confidence.", UsersRound],
  ["02", "Turn busywork into a workflow", "Create repeatable steps for new inquiries, scheduling, service coordination, and the follow-up that keeps good opportunities alive.", Layers3],
  ["03", "Build a calmer operating rhythm", "Give owners and teams a clearer view of what needs attention now, what is coming next, and where the process can improve.", Clock3],
] as const;

export default function Home() {
  return <div className="home-page">
    <section className="home-hero"><div className="container home-hero__grid"><div><p className="eyebrow">HVAC CRM · WORKFLOW AUTOMATION</p><h1>Run the work behind every booked job.</h1><p className="hero-lead">Syntha Airlabs helps HVAC contractors manage leads, customers, scheduling, and follow-up in one clearer operating system.</p><div className="hero-actions"><Link href="/contact" className="button button--primary">Book a demo <ArrowRight size={17} /></Link><Link href="/hvac-crm-software" className="button button--secondary">Explore HVAC CRM <ChevronRight size={17} /></Link></div><p className="hero-note"><CheckCircle2 size={16} /> Built for HVAC teams in the US, UK, Canada, and Australia.</p></div><div className="hero-visual" aria-label="A connected HVAC workflow from lead to booked job"><div className="hero-visual__grid" /><div className="hero-visual__badge">Your next action<br /><strong>is clear.</strong></div><div className="hero-visual__flow"><span>New lead</span><i>→</i><span>Qualified</span><i>→</i><span>Booked</span></div><div className="hero-visual__orb" /></div></div></section>
    <section className="proof-strip"><div className="container proof-strip__inner"><span>Designed for practical growth</span><span>Lead visibility</span><span>Scheduling clarity</span><span>Consistent follow-up</span></div></section>
    <section className="content-section"><div className="container"><div className="section-heading section-heading--split"><div><p className="eyebrow">A CRM for the work HVAC teams actually do</p><h2>Less chasing. More control over the day.</h2></div><p>HVAC businesses move quickly. A call comes in while a technician is on the road, an appointment changes, and a promising lead can get buried in the rush. Syntha Airlabs connects the details and next actions that keep your operation moving, without asking your team to remember everything.</p></div><div className="benefit-grid">{benefits.map(([number, title, body, Icon]) => <article className="benefit-card" key={title}><span className="card-index">{number}</span><Icon size={22} strokeWidth={1.5} className="benefit-card__icon" /><h3>{title}</h3><p>{body}</p><Link href={number === "01" ? "/hvac-crm-software" : number === "02" ? "/hvac-scheduling-software" : "/hvac-lead-management-software"} className="inline-link">Learn more <ArrowRight size={16} /></Link></article>)}</div></div></section>
    <section className="content-section content-section--dark"><div className="container workflow-grid"><div><p className="eyebrow">How it works</p><h2>Connect the signal. Own the next step.</h2><p className="section-copy">Start with the way your team handles inquiries, appointments, and customer communication today. Then shape a workflow that makes the useful path obvious for everyone—from the office to the field.</p><Link href="/pricing" className="button button--light">See plans and fit <ArrowRight size={17} /></Link></div><ol className="step-list step-list--dark"><li><span>01</span><div><strong>Capture the opportunity</strong><p>Bring each inquiry into a shared, useful record.</p></div></li><li><span>02</span><div><strong>Coordinate the work</strong><p>Make ownership, timing, and customer context visible.</p></div></li><li><span>03</span><div><strong>Improve the pattern</strong><p>Use what you learn to make the next week smoother.</p></div></li></ol></div></section>
    <section className="testimonial-section"><div className="container testimonial-section__inner"><div><p className="eyebrow">Proof is built into the process</p><h2>Clarity your customers can feel.</h2></div><blockquote>“When the next step is visible, the whole team can respond like one team.”<cite>— Syntha Airlabs product principle</cite></blockquote><p className="placeholder-note">Customer stories are being collected as the product rolls out. Book a conversation to discuss your own workflow and see what a clearer system could look like.</p></div></section>
    <section className="cta-band"><div className="container cta-band__inner"><div><p className="eyebrow">The next job starts with a better system</p><h2>Make your HVAC operation easier to run.</h2></div><Link href="/contact" className="button button--light">Book a demo <ArrowRight size={17} /></Link></div></section>
  </div>;
}
