import React from "react";
import { ArrowRight, Check } from "lucide-react";
import { Link } from "wouter";

const fitPoints = ["A clearer offer and page structure", "A responsive website or focused landing page", "A more useful path from visitor to enquiry", "A practical foundation for the next stage"];

export default function Pricing() {
  return <div className="page-shell"><section className="page-hero"><div className="container narrow"><p className="eyebrow">PROJECT FIT</p><h1>A clearer digital presence should fit the way your business works.</h1><p className="page-hero__lead">Every business starts from a different place. Syntha Airlabs shapes the scope around your offer, audience, existing presence, and the next useful outcome—not a list of work you do not need.</p><Link href="/contact" className="button button--primary">Talk through your project <ArrowRight size={17} /></Link></div></section><section className="content-section"><div className="container pricing-grid"><div><p className="eyebrow">What your conversation covers</p><h2>Start with the business, then choose the right level of work.</h2><p className="section-copy">A short first conversation helps clarify what you are building, who the website needs to reach, what feels unclear today, and whether the right next step is a focused refresh, a new business website, or a campaign landing page.</p></div><article className="pricing-card"><span className="card-index">SYNTHA / AIRLABS</span><h3>Clarity-first website work</h3><p>Built for founders and growing businesses that want a digital presence with direction.</p><ul>{fitPoints.map((point) => <li key={point}><Check size={17} />{point}</li>)}</ul><Link href="/contact" className="button button--primary">Start a project brief <ArrowRight size={17} /></Link></article></div></section><section className="content-section content-section--tint"><div className="container link-panel"><div><p className="eyebrow">Explore the service paths</p><h2>Start where the biggest gap is today.</h2></div><div className="link-panel__links"><Link href="/website-design-services">Website design services <ArrowRight size={17} /></Link><Link href="/business-website-design">Business website design <ArrowRight size={17} /></Link><Link href="/landing-page-design-services">Landing page design services <ArrowRight size={17} /></Link><Link href="/faq">Read the project FAQs <ArrowRight size={17} /></Link></div></div></section></div>;
}
