import React from "react";
import { ArrowRight, Check } from "lucide-react";
import { Link } from "wouter";

const planPoints = ["Customer and lead context in one place", "Scheduling and follow-up workflows", "A clearer view of ownership and next actions", "A practical rollout shaped around your team"];

export default function Pricing() {
  return <div className="page-shell"><section className="page-hero"><div className="container narrow"><p className="eyebrow">PRICING & FIT</p><h1>A clearer system should fit the way your business works.</h1><p className="page-hero__lead">Syntha Airlabs pricing is shaped around your team, workflow, and stage of growth—not a long list of features you will never use.</p><Link href="/contact" className="button button--primary">Talk through your needs <ArrowRight size={17} /></Link></div></section><section className="content-section"><div className="container pricing-grid"><div><p className="eyebrow">What your conversation covers</p><h2>Start with the work, then choose the right level of support.</h2><p className="section-copy">Every HVAC operation has a different mix of office roles, field capacity, service types, and follow-up habits. A short demo helps us understand the current process and recommend the simplest path that can create useful clarity.</p></div><article className="pricing-card"><span className="card-index">SYNTHA / AIRLABS</span><h3>Workflow-first CRM</h3><p>Built for HVAC contractors who want lead, customer, scheduling, and follow-up work connected.</p><ul>{planPoints.map((point) => <li key={point}><Check size={17} />{point}</li>)}</ul><Link href="/contact" className="button button--primary">Request a demo <ArrowRight size={17} /></Link></article></div></section><section className="content-section content-section--tint"><div className="container link-panel"><div><p className="eyebrow">Explore the product surface</p><h2>See where your biggest gap is today.</h2></div><div className="link-panel__links"><Link href="/hvac-crm-software">HVAC CRM software <ArrowRight size={17} /></Link><Link href="/hvac-scheduling-software">HVAC scheduling software <ArrowRight size={17} /></Link><Link href="/hvac-lead-management-software">HVAC lead management software <ArrowRight size={17} /></Link><Link href="/faq">Read the FAQs <ArrowRight size={17} /></Link></div></div></section></div>;
}
